### ISSUE TITLE
Page selection discard filters

### ISSUE THREAD

**Issue by Stevendeo** [OCamlPro/benchtop#2]
When selecting a given page, the filters disapear. This is because the bottom links are static links not adding to the URL the filter parameters.

**Comment by Halbaroth** [comment]
As I told to Guillaume yesterday, I knew this bug before I created it :p. I will fix it now because it is really annoying :)

**Comment by Halbaroth** [comment]
Fixed by the commit  https://github.com/OCamlPro/benchtop/commit/469c1792c838050c337b71dbf190d9ec4d00cd51
